REVERTED_CHANGE = "Oops!"
FILE_CREATION_MESSAGE = "Might have created a file maybe?"
FILE_DELETION_MESSAGE = "TERMINATE! TERMINATE!"
FOLDER_CREATION_MESSAGE = "zZzzzZz more place for files"
FOLDER_DELETION_MESSAGE = "Less place for files"
OK_MESSAGE = "OK"
FC_NEW_ID = "WHO IS THIS???"
FC_OLD_ID_OLD_PC = "AH I KNOW YOU!"
FC_OLD_ID_NEW_PC = "Why the costume?"
END_CLONE = "ENDING THE CLONE WAR"
END_UPDATES = "NO MORE UPDATES, STAY TUNED FOR MORE"



